# Generated by Django 5.1.4 on 2024-12-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('signed_document', models.FileField(upload_to='signed_contracts/')),
            ],
        ),
    ]
